const bookDatabase = 
{  books : [  { name : "The Way Of Shadows", 
              cover : "/Images/thewayofshadows.jpg",
              author :  "Brent Weeks",
              series :  { name :"The Night Angel Trioligy",  number: "1 [of 3]", completed : true, otherBooksInSeries : ["Beyond The Shadows", "Shadows Edge"] } ,
              genre :  [ "Fantasy", "Fiction" ],
              characters : [ "Azoth", "Durzo Blint", "Elene Cromwyll", "Jarl", "Logan Gyre", "Rimbold Drake", "Viridiana Sovari", 
                            "Gwinvere Kirena", "Feir Cousat", "Dorian Ursuul", "Solonariwan Tofusin", "Jenine Gyre", "Neph Dada"],
              language : "English",
              published : new Date(2008, 9, 1),
              publisher : "Orbit"
            }, 
            { name : "Beyond The Shadows",
            cover : "/Images/beyondtheshadows.jpg",
              author : "Brent Weeks",
              series : { name :"The Night Angel Trioligy", number: "2 [of 3]", completed : true, otherBooksInSeries : ["The Way Of Shadows", "Shadows Edge"] } ,
              genre :  [ "Fantasy", "Fiction" ],
              characters : [ "Azoth", "Durzo Blint", "Elene Cromwyll", "Jarl", "Logan Gyre", "Rimbold Drake", "Viridiana Sovari", 
                            "Gwinvere Kirena", "Feir Cousat", "Dorian Ursuul", "Solonariwan Tofusin", "Jenine Gyre", "Neph Dada"],
              language : "English",
              published : new Date(2008, 9, 28),
              publisher : "Orbit"
            },
            { name : "Shadows Edge",
            cover : "/Images/shadowsedge.jpg",
              author :  "Brent Weeks", 
              series :  { name :"The Night Angel Trioligy", number: "3 [of 3]", completed : true, otherBooksInSeries : ["The Way Of Shadows", "Beyond The Shadows"]  } ,
              genre :  [ "Fantasy", "Fiction" ],
              language : "English",
              characters : [ "Azoth", "Durzo Blint", "Elene Cromwyll", "Jarl", "Logan Gyre", "Rimbold Drake", "Viridiana Sovari", 
                            "Gwinvere Kirena", "Feir Cousat", "Dorian Ursuul", "Solonariwan Tofusin", "Jenine Gyre", "Neph Dada"],
              published : new Date(2008, 10, 25),
              publisher : "Orbit"
            },
            { name : "Ship Of Magic",
            cover : "/Images/shipofmagic.jpg",
              author : "Robin Hobb",
              series : { name : "The Live Ship Traders", number : "1 [of 3]", completed: true,  otherBooksInSeries : ["The Mad Ship", "Ship Of Destiny"] } ,
              genre : [ "Fantasy", "Fiction" ],
              language : "English",
              characters : [ "Althea Vestrit", "Ephron Vestrit", "Ronica Vestrit", "Keffria Vestrit", "Kyle Haven", "Wintrow Haven", "Malta Haven", 
                            "Vivacia", "Paragon (Liveship)", "Brashen Trell", "Amber (Liveship Traders)", "Kennit"],
              published: new Date(1998, 2, 2),
              publisher : "Bantam"
            },
            { name : "Dragons Of Winter Night",
            cover : "/Images/dragonswinternight.jpg",
              author : [ "Margaret Weis",  "Tracy Hickman" ],
              series : { name : "The DragonLance Saga", number : "2 [of 3]", completed: true,  otherBooksInSeries : ["Dragons Of Autumn Twilight", "Dragons Of Spring Dawning"] } ,
              genre : [ "Fantasy", "Fiction", "Epic Fantasy"],
              characters : [ "Tanis Half-Elven", "Sturm Brightblade", "Flint Fireforge", "Tika Waylan", "Caramon Majere", "Raistlin Majere", "Lauralanthalasa", "Kitiara uth Matar", "Tasslehoff Burrfoot", 
                            "Alhana Starbreeze"," Riverwind", "Goldmoon", "Kylan Iverson", "Garn", "Aylaen", "Norgaard", "Wulfe", "Raegar", "Gilthanas", "Derek Crownguard"],
              language : "English",
              published: new Date(1985, 6, 1),
              publisher : "TSR"
            },
            { name : "The Serpent Mage ",
            cover : "/Images/serpentmage.jpg",
              author : [ "Margaret Weis",  "Tracy Hickman" ],
              series : { name : "The Death Gate Cycle", number : "4 [of 7]", completed: true, otherBooksInSeries : ["Dragon Wing", "Elven Star", " Fire Sea", "The Hand Of Chaos", "Into The Labyrinth", "The Seventh Gate"] } ,
              genre : [ "Fantasy", "Fiction", "Epic Fantasy"],
              language : "English",
              characters : ["Haplo", "Alfred", "Devon", "Grundle", "Alake", "Sang-Drax"],
              published: new Date(1992, 0, 1),
              publisher : "Bantam"
            },
            { name : "Menneskefluene",
            cover : "/Images/menneskefluene.jpg",
              author : "Hans Olav Lahlum",
              series : { name : "K2 og Patricia", number : "1 [of 12]", completed: false, otherBooksInSeries : ["Satelittmenneskene", "Svanemordet"] } ,
              genre : [ "Crime", "Fiction"],
              language : "Norwegian",
              characters : ["Kolbjørn Kristiansen (K2)", "Paticia"],
              published: new Date(2014, 5, 1),
              publisher : "Cappelen"
            },{
               name : "The Final Empire",
               cover : "/Images/thefinalempire.jpg",
              author : "Brandon Sanderson",
              series : { name : "Mistborn", number : "1 [of 3]", completed: true, otherBooksInSeries : ["The Well of Ascension", "The Hero of Ages"] } ,
              genre : [ "Fantasy", "Fiction"],
              language : "English",
              characters : ["Marsh", "Vin", "Elend Venture", "Sazed", "Kelsier", "Dockson", "Hammond", "Breeze", "Clubs", "Spook", "The Lord Ruler", "Lord Renoux", "Yeden", "OreSeur"],
              published: new Date(2006, 5, 17),
              publisher : "Tor Books"
            }
         ],
  authors : [ { name: "Margaret Weis", 
                image: "/Images/margaretweis.png", 
                born: new Date(1948, 2, 16), 
                location : "Independence, Missouri U.S",
                gender : "female",
              }, 
              { name: "Tracy Hickman", 
                image: "/Images/tracyhickman.png", 
                born: new Date(1955, 10, 25), 
                location : "Salt Lake City, Utah U.S",
                gender : "male"
              }, 
              { name : "Brent Weeks", 
                image: "/Images/brentweeks.png", 
                born : new Date(1977, 2, 7), 
                location : "Montana U.S" ,
                gender : "male"
              },

              { name: "Robin Hobb", 
                image: "/Images/robinhobb.png", 
                born: new Date(1952, 2, 5), 
                location : "Berkley, California U.S", 
                gender : "female",
                penAs : ["Robin Hobb", "Megan Lindholm" ]
              },
              {
                name : "Brandon Sanderson",
                image : "/Images/brandonsanderson.png",
                born : new Date(1975, 11, 19),
                location : "Lincoln, Nebraska U.S",
                gender : "male",
                pensAs : null
              } 
            ],

  publishers: [ { name : "Orbit",
                  fullName : "Orbit UK",
                  founded : new Date(1974),
                  countryOfOrigin : "United Kingdom",
                  
                  webPage : "https://www.orbit-books.co.uk/",
                },
                { name : "Bantam",
                  fullName : "Batam Books",
                  founded : new Date(1945),
                  countryOfOrigin : "United States",
                  founders :  ["Walter B. Pitkin, Jr." , "Sidney B. Kramer"," Ian Ballantine","Betty Ballantine"] ,
                  webPage : "https://www.randomhousebooks.com/imprint/bantam-books/"
                },
                { name : "TSR",
                  fullName : "TSR Inc. (now : Wizards Of The Coast)",
                  founded : new Date(1983),
                  countryOfOrigin : "United States",
                  founders :  ["Gary Gygax", "Don Kaye"],
                  webPage : "https://company.wizards.com/en"
                }
              ]
};

export { bookDatabase };